version: '3'
services:
  app:
    container_name: FastAPI
    build: ./app
    volumes:
      - ./app:/app
      - ./log:/var/log
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      TZ: "Asia/Tokyo"

  web:
    container_name: Nginx
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Tokyo"